# Generated by Django 5.2.7 on 2026-04-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_curso_material_mentoriaaula_modulo_aula_perfilaluno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilaluno',
            name='telefone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
