# Generated by Django 6.0.2 on 2026-09-14 23:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_perfilaluno_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('slug', models.SlugField(unique=True)),
                ('setor', models.CharField(blank=True, max_length=120)),
                ('situacao', models.TextField()),
                ('problema', models.TextField()),
                ('diagnostico', models.TextField()),
                ('abordagem', models.TextField()),
                ('resultado', models.TextField()),
                ('aprendizado', models.TextField(blank=True)),
                ('publicado', models.BooleanField(default=False)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Cases',
                'ordering': ['ordem', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaConteudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('descricao', models.CharField(blank=True, max_length=240)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoria de conteúdo',
                'verbose_name_plural': 'Categorias de conteúdo',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Depoimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('cargo', models.CharField(blank=True, max_length=120)),
                ('empresa', models.CharField(blank=True, max_length=160)),
                ('texto', models.TextField()),
                ('ativo', models.BooleanField(default=False)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagina', models.CharField(choices=[('home', 'Página inicial'), ('cursos', 'Formações'), ('curso_cultura', 'Cultura de Segurança'), ('curso_teste', 'Perfil e Carreira'), ('mentoria', 'Mentoria'), ('empresas', 'Para empresas')], max_length=30)),
                ('pergunta', models.CharField(max_length=220)),
                ('resposta', models.TextField()),
                ('ativa', models.BooleanField(default=True)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Pergunta frequente',
                'verbose_name_plural': 'Perguntas frequentes',
                'ordering': ['pagina', 'ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MaterialGratuito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('slug', models.SlugField(unique=True)),
                ('descricao', models.CharField(max_length=320)),
                ('arquivo_url', models.URLField(blank=True)),
                ('ativo', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Material gratuito',
                'verbose_name_plural': 'Materiais gratuitos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('origem', models.CharField(default='site', max_length=80)),
                ('ativo', models.BooleanField(default=True)),
                ('consentimento_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inscrição na newsletter',
                'verbose_name_plural': 'Inscrições na newsletter',
                'ordering': ['-consentimento_em'],
            },
        ),
        migrations.AddField(
            model_name='mentoriacontato',
            name='cargo',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='mentoriacontato',
            name='consentimento_privacidade',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mentoriacontato',
            name='empresa',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='mentoriacontato',
            name='origem',
            field=models.CharField(default='site', max_length=80),
        ),
        migrations.AddField(
            model_name='mentoriacontato',
            name='telefone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='mentoriacontato',
            name='tipo_interesse',
            field=models.CharField(choices=[('formacao', 'Quero conhecer uma formação'), ('mentoria', 'Quero conhecer a mentoria'), ('treinamento_empresa', 'Quero treinamento para empresa'), ('palestra', 'Quero conversar sobre uma palestra'), ('outro', 'Outro assunto')], default='mentoria', max_length=40),
        ),
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('slug', models.SlugField(unique=True)),
                ('resumo', models.CharField(max_length=320)),
                ('conteudo', models.TextField()),
                ('autor', models.CharField(default='Alan Silvério', max_length=120)),
                ('tempo_leitura', models.PositiveSmallIntegerField(default=5)),
                ('imagem_url', models.URLField(blank=True)),
                ('imagem_alt', models.CharField(blank=True, max_length=180)),
                ('meta_titulo', models.CharField(blank=True, max_length=180)),
                ('meta_descricao', models.CharField(blank=True, max_length=320)),
                ('publicado', models.BooleanField(default=False)),
                ('publicado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artigos', to='core.categoriaconteudo')),
            ],
            options={
                'ordering': ['-publicado_em'],
            },
        ),
    ]
